bit_mask =  {'BAD': 1,
             'BRIGHT_OBJECT': 512,
             'CLIPPED': 1024,
             'CR': 8,
             'CROSSTALK': 2048,
             'DETECTED': 32,
             'DETECTED_NEGATIVE': 64,
             'EDGE': 16,
             'INTRP': 4,
             'NOT_DEBLENDED': 4096,
             'NO_DATA': 256,
             'SAT': 2,
             'SUSPECT': 128,
             'UNMASKEDNAN': 8192}
